# Uncomment the next line to define a global platform for your project
platform :ios, '16.1'

flutter_application_path = '../flutter_ads_isssue_700'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'googleads-mobile-issue-700' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)
  post_install do |installer|
    flutter_post_install(installer) if defined?(flutter_post_install)
  end
end
